import { themeBridge } from './theme-bridge.js'
import { contextBridge, ipcRenderer } from 'electron'
const invoke = (ch, ...a) => ipcRenderer.invoke(ch, ...a)
const send = (ch, ...a) => ipcRenderer.send(ch, ...a)
const on = (ch, cb) => { ipcRenderer.on(ch, (_, d) => cb(d)); return () => ipcRenderer.removeAllListeners(ch) }

contextBridge.exposeInMainWorld('ft', {
  window: { minimize: () => send('window:minimize'), maximize: () => send('window:maximize'), close: () => send('window:close') },
  device: { list: () => invoke('device:list'), info: a => invoke('device:info', a), screenshot: a => invoke('device:screenshot', a) },
  adb: {
    version:    () => invoke('adb:version'), shell: a => invoke('adb:shell', a), push: a => invoke('adb:push', a), pull: a => invoke('adb:pull', a), reboot: a => invoke('adb:reboot', a) },
  files: { list: a => invoke('files:list', a), delete: a => invoke('files:delete', a), mkdir: a => invoke('files:mkdir', a), import: a => invoke('files:import', a), export: a => invoke('files:export', a) },
  apps: { list: a => invoke('apps:list', a), uninstall: a => invoke('apps:uninstall', a), extract: a => invoke('apps:extract', a), clearData: a => invoke('apps:clear-data', a), forceStop: a => invoke('apps:force-stop', a), enable: a => invoke('apps:enable', a), disable: a => invoke('apps:disable', a) },
  sideload: {
    apk:           a  => invoke('sideload:apk', a),
    xapk:          a  => invoke('sideload:xapk', a),
    ipa:           a  => invoke('sideload:ipa', a),
    pickApk:       () => invoke('sideload:pick-apk'),
    pickIpa:       () => invoke('sideload:pick-ipa'),
    analyzeIpa:    () => invoke('sideload:analyze-ipa'),
    analyzeIpaPath:a  => invoke('sideload:analyze-ipa-path', a),
    installIosDirect: a => invoke('sideload:install-ios-direct', a),
    ipatoolDownload:  a => invoke('sideload:ipatool-download', a),
    openDownloads: () => invoke('sideload:open-downloads'),
    checkIosTools: () => invoke('sideload:check-ios-tools'),
  },
  debloat: { presets: () => invoke('debloat:presets'), scan: a => invoke('debloat:scan', a), apply: a => invoke('debloat:apply', a) },
  backup: { create: a => invoke('backup:create', a), restore: a => invoke('backup:restore', a) },
  privacy: { permissions: a => invoke('privacy:permissions', a), revoke: a => invoke('privacy:revoke', a), pushHosts: a => invoke('privacy:push-hosts', a), setDns: a => invoke('privacy:set-dns', a), scanTrackers: a => invoke('privacy:scan-trackers', a), notificationLog: a => invoke('privacy:notification-log', a) },
  system: { dpi: a => invoke('system:dpi', a), resolution: a => invoke('system:resolution', a), resetDisplay: a => invoke('system:reset-display', a), batteryInfo: a => invoke('system:battery-info', a), injectInput: a => invoke('system:input-inject', a), bootloaderStatus: a => invoke('system:bootloader-status', a) },
  network: { info: a => invoke('network:info', a), carrierInfo: a => invoke('network:carrier-info', a), portScan: a => invoke('network:port-scan', a), proxy: a => invoke('network:proxy', a) },
  extract: { detect: () => invoke('extract:detect'), adbWifi: a => invoke('extract:adb-wifi', a), lockdownScan: () => invoke('extract:lockdown-scan'), lockdownConnect: a => invoke('extract:lockdown-connect', a), start: a => invoke('extract:start', a), edlDetect: () => invoke('extract:edl-detect'), mtkDetect: () => invoke('extract:mtk-detect'), checkm8: a => invoke('extract:checkm8', a), icloud: a => invoke('extract:icloud', a), parseMessages: a => invoke('extract:parse-messages', a), parseWhatsapp: a => invoke('extract:parse-whatsapp', a) },
  rom: { search: a => invoke('rom:search', a), deviceList: a => invoke('rom:device-list', a), download: a => invoke('rom:download', a), verify: a => invoke('rom:verify', a), flashAdb: a => invoke('rom:flash-adb', a), flashFastboot: a => invoke('rom:flash-fastboot', a), stockSources: a => invoke('rom:stock-sources', a) },
  rombuild: { open: () => invoke('rombuild:open'), inspect: a => invoke('rombuild:inspect', a), extract: a => invoke('rombuild:extract', a), listApps: a => invoke('rombuild:list-apps', a), removeApps: a => invoke('rombuild:remove-apps', a), addApp: a => invoke('rombuild:add-app', a), patchMagisk: a => invoke('rombuild:patch-magisk', a), patchBoot: a => invoke('rombuild:patch-boot', a), repack: a => invoke('rombuild:repack', a), buildGsi: a => invoke('rombuild:build-gsi', a), sign: a => invoke('rombuild:sign', a), cleanup: a => invoke('rombuild:cleanup', a) , bakeHosts: a => invoke('rombuild:bake-hosts', a) },
  mirror: { start: a => invoke('mirror:start', a), stop: a => invoke('mirror:stop', a), list: () => invoke('mirror:list'), record: a => invoke('mirror:record', a) },
  adblib: { categories: () => invoke('adblib:categories'), commands: a => invoke('adblib:commands', a), all: () => invoke('adblib:all'), run: a => invoke('adblib:run', a) },
  twrp: { search: a => invoke('twrp:search', a), links: a => invoke('twrp:links', a), flash: a => invoke('twrp:flash', a), bootTemp: a => invoke('twrp:boot-temp', a) },
  magisk: { status: a => invoke('magisk:status', a), modules: () => invoke('magisk:modules'), installed: a => invoke('magisk:installed', a), install: a => invoke('magisk:install', a), remove: a => invoke('magisk:remove', a), toggle: a => invoke('magisk:toggle', a) },
  media: { ringtone: a => invoke('media:ringtone', a), pushRingtone: a => invoke('media:push-ringtone', a), convertHeic: a => invoke('media:convert-heic', a), exportSms: a => invoke('media:export-sms', a), schedulePermReset: a => invoke('media:schedule-perm-reset', a) },
  appupdate: { check: a => invoke('appupdate:check', a), fdroid: a => invoke('appupdate:fdroid', a), installed: a => invoke('appupdate:installed', a) },
  forensics: { export: a => invoke('forensics:export', a) },
  transfer: { devices: () => invoke('transfer:devices'), start: a => invoke('transfer:start', a) },
  testpoints: { all: () => invoke('testpoints:all'), search: a => invoke('testpoints:search', a) },
  waterdamage: { guide: () => invoke('waterdamage:guide') },
  ota: { info: a => invoke('ota:info', a), save: a => invoke('ota:save', a), sources: a => invoke('ota:sources', a) },
  repair: { enable: a => invoke('repair:enable', a) },
  dialog: { openFile: opts => invoke('dialog:open-file', opts), openDir: () => invoke('dialog:open-dir') },
  iosDiag: { run: () => invoke('ios:diagnose'), triggerTrust: a => invoke('ios:trigger-trust', a) },
  iosPair: { pair: a => invoke('ios:pair', a), validate: a => invoke('ios:pair:validate', a), unpair: a => invoke('ios:pair:unpair', a), list: () => invoke('ios:pair:list') },
  theme: {
    get:              ()       => invoke('theme:get'),
    defaults:         ()       => invoke('theme:defaults'),
    set:              patch    => invoke('theme:set', patch),
    reset:            ()       => invoke('theme:reset'),
    export:           ()       => invoke('theme:export'),
    import:           ()       => invoke('theme:import'),
    fontsList:        ()       => invoke('theme:fonts:list'),
    fontsInstall:     ()       => invoke('theme:fonts:install'),
    fontsRemove:      filename => invoke('theme:fonts:remove', filename),
    fontsDir:         ()       => invoke('theme:fonts:dir'),
    fontRead:         filename => invoke('theme:fonts:read', filename),
    uploadLogo:       ()       => invoke('theme:upload:logo'),
    uploadBackground: ()       => invoke('theme:upload:background'),
    uploadThumbnail:  ()       => invoke('theme:upload:thumbnail'),
    uploadFavicon:    ()       => invoke('theme:upload:favicon'),
    assetRead:        filePath => invoke('theme:asset:read', filePath),
    onChange:         cb       => on('theme:current', cb),
  },
  theme: themeBridge,
  scrcpy: {
    isAvailable: () => invoke('mirror:available'),
    start: a => invoke('mirror:start', a),
    stop: a => invoke('mirror:stop', a),
    list: () => invoke('mirror:list'),
    record: a => invoke('mirror:record', a),
    getPresets: () => invoke('mirror:presets'),
  },
  bootloader: {
    getGuide: a => invoke('bootloader:guide', a),
    executeCmd: a => invoke('bootloader:cmd', a),
    getStatus: a => invoke('system:bootloader-status', a),
  },
  kernel: {
    getCurrentInfo: a => invoke('kernel:info', a),
    getSources: a => invoke('kernel:sources', a),
    flash: a => invoke('kernel:flash', a),
  },
  permscheduler: {
    list: () => invoke('permscheduler:list'),
    schedule: a => invoke('permscheduler:add', a),
    cancel: a => invoke('permscheduler:remove', a),
    toggle: a => invoke('permscheduler:toggle', a),
  },
  smspdf: {
    export: a => invoke('smspdf:export', a),
  },
  updater: {
    check: () => invoke('updater:check'),
    clearCache: () => invoke('updater:clear-cache'),
  },
  ios: {
    shsh: {
      getFirmwares: a => invoke('ios:shsh:getFirmwares', a),
      getSigned:    a => invoke('ios:shsh:getSigned', a),
      save:         a => invoke('ios:shsh:save', a),
      listSaved:    () => invoke('ios:shsh:listSaved'),
    openDir:      () => invoke('ios:shsh:openDir'),
    import:       () => invoke('ios:shsh:import'),
    },
    ipsw: {
      search:   a => invoke('ios:ipsw:search', a),
      getOta:   a => invoke('ios:ipsw:getOta', a),
      download: a => invoke('ios:ipsw:download', a),
      restore:  a => invoke('ios:ipsw:restore', a),
    },
    jb: {
      getOptions:      a => invoke('ios:jb:getOptions', a),
      trollstoreCheck: a => invoke('ios:jb:trollstoreCheck', a),
      isJailbroken:    a => invoke('ios:jb:isJailbroken', a),
      palera1n:        a => invoke('ios:jb:palera1n', a),
    },
    cydia: {
      repos:    () => invoke('ios:cydia:repos'),
      packages: a  => invoke('ios:cydia:packages', a),
      download: a  => invoke('ios:cydia:download', a),
      install:  a  => invoke('ios:cydia:install', a),
    },
    ssh: {
      startProxy: a => invoke('ios:ssh:startProxy', a),
      commands:   () => invoke('ios:ssh:commands'),
    },
    backup: {
      isEncrypted:   a => invoke('ios:backup:isEncrypted', a),
      decrypt:       a => invoke('ios:backup:decrypt', a),
      contents:      a => invoke('ios:backup:contents', a),
      extractPhotos: a => invoke('ios:backup:extractPhotos', a),
    },
    icloud: {
      authenticate: a => invoke('ios:icloud:authenticate', a),
      pull:         a => invoke('ios:icloud:pull', a),
      services:     () => invoke('ios:icloud:services'),
    },
    diagnostics: {
      battery:   a => invoke('ios:diagnostics:battery', a),
      storage:   a => invoke('ios:diagnostics:storage', a),
      gestalt:   a => invoke('ios:diagnostics:gestalt', a),
      syslog:    a => invoke('ios:diagnostics:syslog', a),
      crashLogs: a => invoke('ios:diagnostics:crashLogs', a),
    },
    profiles: {
      list:    a => invoke('ios:profiles:list', a),
      install: a => invoke('ios:profiles:install', a),
      remove:  a => invoke('ios:profiles:remove', a),
    },
    media: {
      createRingtone: a => invoke('ios:media:createRingtone', a),
      pushRingtone:   a => invoke('ios:media:pushRingtone', a),
    },
  },
  logcat: {
    snapshot:  a => invoke('logcat:snapshot', a),
    clear:     a => invoke('logcat:clear', a),
    processes: a => invoke('logcat:processes', a),
    save:      a => invoke('logcat:save', a),
    start:     a => invoke('logcat:start', a),
    stop:      a => invoke('logcat:stop', a),
  },
  apk: {
    analyse:          a => invoke('apk:analyse', a),
    compare:          a => invoke('apk:compare', a),
    extractFromDevice:a => invoke('apk:extract-from-device', a),
  },
  sqlite: {
    open:        a => invoke('sqlite:open', a),
    query:       a => invoke('sqlite:query', a),
    write:       a => invoke('sqlite:write', a),
    exportCsv:   a => invoke('sqlite:export-csv', a),
    findAppDbs:  a => invoke('sqlite:find-app-dbs', a),
    pullAndOpen: a => invoke('sqlite:pull-and-open', a),
  },
  clipboard: {
    get:       a => invoke('clipboard:get', a),
    set:       a => invoke('clipboard:set', a),
    startSync: a => invoke('clipboard:start-sync', a),
    stopSync:  () => invoke('clipboard:stop-sync'),
  },
  hwdiag: {
    sensors:      a => invoke('hwdiag:sensors', a),
    gpu:          a => invoke('hwdiag:gpu', a),
    usbSpeed:     a => invoke('hwdiag:usb-speed', a),
    storageSpeed: a => invoke('hwdiag:storage-speed', a),
    displayTest:  a => invoke('hwdiag:display-test', a),
    speakerTest:  a => invoke('hwdiag:speaker-test', a),
  },
  wifi: {
    extract: a => invoke('wifi:extract', a),
    export:  a => invoke('wifi:export', a),
  },
  certs: {
    listUser:   a => invoke('certs:list-user', a),
    listSystem: a => invoke('certs:list-system', a),
    install:    a => invoke('certs:install', a),
    remove:     a => invoke('certs:remove', a),
    mitmInfo:   a => invoke('certs:mitm-info', a),
  },
  frida: {
    available:   () => invoke('frida:available'),
    version:     () => invoke('frida:version'),
    processes:   a  => invoke('frida:processes', a),
    templates:   () => invoke('frida:templates'),
    pushServer:  a  => invoke('frida:push-server', a),
    startServer: a  => invoke('frida:start-server', a),
    stopServer:  a  => invoke('frida:stop-server', a),
    inject:      a  => invoke('frida:inject', a),
  },
  intent: {
    send:    a => invoke('intent:send', a),
    presets: () => invoke('intent:presets'),
  },
  layout: {
    dump:       a => invoke('layout:dump', a),
    find:       a => invoke('layout:find', a),
    screenshot: a => invoke('layout:screenshot', a),
  },
  mockloc: {
    enable:  a => invoke('mockloc:enable', a),
    set:     a => invoke('mockloc:set', a),
    stop:    a => invoke('mockloc:stop', a),
    presets: () => invoke('mockloc:presets'),
  },
  clone: {
    app: a => invoke('clone:app', a),
  },
  traffic: {
    uid:         a => invoke('traffic:uid', a),
    connections: a => invoke('traffic:connections', a),
    raw:         a => invoke('traffic:raw', a),
  },
  usb: {
    drives: {
      list:   () => invoke('usb:drives:list'),
      health: a  => invoke('usb:drives:health', a),
      format: a  => invoke('usb:drives:format', a),
    },
    catalog: {
      all:    () => invoke('usb:catalog:all'),
      latest: a  => invoke('usb:catalog:latest', a),
    },
    tools: {
      list:        () => invoke('usb:tools:list'),
      download:    a  => invoke('usb:tools:download', a),
      launch:      a  => invoke('usb:tools:launch', a),
      openWebsite: a  => invoke('usb:tools:open-website', a),
    },
    iso: {
      list:    () => invoke('usb:iso:list'),
      download:a  => invoke('usb:iso:download', a),
      add:     () => invoke('usb:iso:add'),
      verify:  a  => invoke('usb:iso:verify', a),
      delete:  a  => invoke('usb:iso:delete', a),
      dir:     () => invoke('usb:iso:dir'),
      openDir: () => invoke('usb:iso:open-dir'),
    },
    ventoy: {
      check:   a => invoke('usb:ventoy:check', a),
      copyIso: a => invoke('usb:ventoy:copy-iso', a),
      install: a => invoke('usb:ventoy:install', a),
    },
    write: a => invoke('usb:write', a),
  },
  flash: {
    tools:  { list: () => invoke('flash:tools:list') },
    wizard: { cases: () => invoke('flash:wizard:cases'), keys: () => invoke('flash:wizard:keys') },
    tool:   { open: a => invoke('flash:tool:open', a), download: a => invoke('flash:tool:download', a) },
    write:  a => invoke('flash:write', a),
    cancel: () => invoke('flash:write:cancel'),
    verify: a => invoke('flash:write:verify', a),
  },
  iosUnlock: {
    methods:       a  => invoke('ios:unlock:methods', a),
    enterDfu:      a  => invoke('ios:unlock:enter-dfu', a),
    enterRecovery: a  => invoke('ios:unlock:enter-recovery', a),
    exitRecovery:  a  => invoke('ios:unlock:exit-recovery', a),
    bypassMethods: () => invoke('ios:bypass:methods'),
    activationCheck: a => invoke('ios:activation:check', a),
  },
  terminal: {
    create:     a  => invoke('terminal:create', a),
    write:      a  => invoke('terminal:write', a),
    kill:       a  => invoke('terminal:kill', a),
    listShells: () => invoke('terminal:list-shells'),
    adb:        a  => invoke('terminal:adb', a),
    run:        a  => invoke('terminal:run', a),
  },
  iosFull: {
    trust: {
      pair:     a  => invoke('ios:forcetrust:pair', a),
      validate: a  => invoke('ios:forcetrust:validate', a),
      list:     () => invoke('ios:forcetrust:list'),
      export:   a  => invoke('ios:forcetrust:export', a),
      import:   () => invoke('ios:forcetrust:import'),
    },
    keychain: {
      backup:     a  => invoke('ios:keychain:backup', a),
      jailbroken: a  => invoke('ios:keychain:jailbroken', a),
      summarize:  a  => invoke('ios:keychain:summarize', a),
      openDir:    () => invoke('ios:keychain:open-dir'),
    },
    syslog: {
      start:    a  => invoke('ios:syslog:start', a),
      stop:     () => invoke('ios:syslog:stop'),
      snapshot: a  => invoke('ios:syslog:snapshot', a),
      save:     a  => invoke('ios:syslog:save', a),
    },
    apps: {
      list:      a  => invoke('ios:apps:list', a),
      install:   a  => invoke('ios:apps:install', a),
      uninstall: a  => invoke('ios:apps:uninstall', a),
      extract:   a  => invoke('ios:apps:extract', a),
    },
    files: {
      list:   a  => invoke('ios:files:list', a),
      pull:   a  => invoke('ios:files:pull', a),
      push:   a  => invoke('ios:files:push', a),
      photos: a  => invoke('ios:files:photos', a),
    },
    system: {
      info:       a  => invoke('ios:system:info', a),
      screenshot: a  => invoke('ios:system:screenshot', a),
      restart:    a  => invoke('ios:system:restart', a),
      shutdown:   a  => invoke('ios:system:shutdown', a),
      battery:    a  => invoke('ios:system:battery', a),
      setname:    a  => invoke('ios:system:setname', a),
    },
    net: {
      proxy: a  => invoke('ios:net:proxy', a),
      info:  a  => invoke('ios:net:info', a),
    },
    forceTrust:      a => invoke('ios:force-trust', a),
    keychainInfo:    a => invoke('ios:keychain:info', a),
    keychainExtract: a => invoke('ios:keychain:extract', a),
    messagesExport:  a => invoke('ios:messages:export', a),
    forensicsExtract:a => invoke('ios:forensics:extract', a),
    wifiExtract:     a => invoke('ios:wifi:extract', a),
    contactsExport:  a => invoke('ios:contacts:export', a),
    photosExport:    a => invoke('ios:photos:export', a),
    networkInfo:     a => invoke('ios:network:info', a),
    carrierInfo:     a => invoke('ios:network:carrier', a),
    privacyScan:     a => invoke('ios:privacy:scan', a),
    backupCreate:    a => invoke('ios:backup:create', a),
    backupRestore:   a => invoke('ios:backup:restore', a),
    battery:         a => invoke('ios:system:battery', a),
    info:            a => invoke('ios:system:info', a),
    screenshot:      a => invoke('ios:system:screenshot', a),
  },
  iosFiles: {
    list:   a => invoke('ios:files:list', a),
    pull:   a => invoke('ios:files:pull', a),
    push:   a => invoke('ios:files:push', a),
    delete: a => invoke('ios:files:delete', a),
  },
  iosApps: {
    list:      a => invoke('ios:apps:list', a),
    uninstall: a => invoke('ios:apps:uninstall', a),
    extract:   a => invoke('ios:apps:extract', a),
  },
  quick: {
    screenshot:  a => invoke('quick:screenshot', a),
    reboot:      a => invoke('quick:reboot', a),
    clearCache:  a => invoke('quick:clear-cache', a),
    battery:     a => invoke('quick:battery', a),
    wifiToggle:  a => invoke('quick:wifi-toggle', a),
    airplane:    a => invoke('quick:airplane', a),
    brightness:  a => invoke('quick:brightness', a),
    volume:      a => invoke('quick:volume', a),
    lock:        a => invoke('quick:lock', a),
    home:        a => invoke('quick:home', a),
    back:        a => invoke('quick:back', a),
    recent:      a => invoke('quick:recent', a),
    wake:        a => invoke('quick:wake', a),
    installApk:  a => invoke('quick:install-apk', a),
    topApps:     a => invoke('quick:top-apps', a),
  },
  adbBuilder: {
    run: a => invoke('adb:run-custom', a),
  },
  fastboot: {
    devices:  ()  => invoke('fastboot:devices'),
    flash:    a   => invoke('fastboot:flash', a),
    command:  a   => invoke('fastboot:command', a),
    reboot:   a   => invoke('fastboot:reboot', a),
    getvar:   a   => invoke('fastboot:getvar', a),
  },
  dns: {
    get: a => invoke('dns:get', a),
    set: a => invoke('dns:set', a),
  },
  batteryHist: {
    record: a => invoke('battery:history:record', a),
    get:    a => invoke('battery:history:get', a),
    clear:  a => invoke('battery:history:clear', a),
  },
  appClone: {
    clone: a => invoke('app:clone', a),
    info:  a => invoke('app:info', a),
  },
  speedtest: {
    run:  a => invoke('speedtest:run', a),
    ping: a => invoke('speedtest:ping', a),
  },
  wireless: {
    pair:       a => invoke('wireless:pair', a),
    connect:    a => invoke('wireless:connect', a),
    disconnect: a => invoke('wireless:disconnect', a),
    tcpip:      a => invoke('wireless:tcpip', a),
    getIp:      a => invoke('wireless:get-ip', a),
  },
  buildprop: {
    read: a => invoke('buildprop:read', a),
    set:  a => invoke('buildprop:set', a),
    get:  a => invoke('buildprop:get', a),
  },
  hosts: {
    read:          a => invoke('hosts:read', a),
    write:         a => invoke('hosts:write', a),
    fetchBlocklist:a => invoke('hosts:fetch-blocklist', a),
  },
  deviceHealth: {
    full: a => invoke('health:full', a),
  },
  processManager: {
    list:  a => invoke('process:list', a),
    kill:  a => invoke('process:kill', a),
    top:   a => invoke('process:top', a),
  },
  appBackup: {
    list:        a => invoke('appbackup:list', a),
    pullApk:     a => invoke('appbackup:pull-apk', a),
    backupData:  a => invoke('appbackup:backup-data', a),
    restore:     a => invoke('appbackup:restore', a),
    pullData:     a => invoke('appbackup:pull-data', a),
    restoreApk:   a => invoke('appbackup:restore-apk', a),
    listSaved:    () => invoke('appbackup:list-saved'),
    openFolder:   () => invoke('appbackup:open-folder'),
  },
  hashTool: {
    file:    a => invoke('hash:file', a),
    verify:  a => invoke('hash:verify', a),
    apkCert: a => invoke('hash:apk-cert', a),
  },
  notifLogger: {
    start: a => invoke('notif:start', a),
    stop:  a => invoke('notif:stop', a),
    get:   a => invoke('notif:get', a),
    clear: a => invoke('notif:clear', a),
  },
  proc: {
    list:   a => invoke('proc:list', a),
    kill:   a => invoke('proc:kill', a),
    detail: a => invoke('proc:detail', a),
  },
  crypto: {
    hashFile:       () => invoke('crypto:hash-file'),
    verify:         a  => invoke('crypto:verify', a),
    apkCert:        a  => invoke('crypto:apk-cert', a),
    deviceApkCert:  a  => invoke('crypto:device-apk-cert', a),
  },
  onboard: {
    checkTools:   () => invoke('onboard:check-tools'),
    checkDrivers: () => invoke('onboard:check-drivers'),
    runInstall:   () => invoke('onboard:run-install'),
  },
  discover: {
    usbDevices:    () => invoke('discover:usb-devices'),
    fastboot:      () => invoke('discover:fastboot-devices'),
    networkScan:   a  => invoke('discover:network-scan', a),
    enableAdb:     a  => invoke('discover:enable-adb', a),
    connectWifi:   a  => invoke('discover:adb-connect-wifi', a),
  },
  jailbreak: {
    detectDevice:      ()  => invoke('jailbreak:detect-device'),
    downloadCheckn1x:  ()  => invoke('jailbreak:download-checkn1x'),
    flashCheckn1x:     a  => invoke('jailbreak:flash-checkn1x', a),
    openFolder:        ()  => invoke('jailbreak:open-folder'),
    dfuHelp:           a  => invoke('jailbreak:dfu-help', a),
    sideloadIpa:       a  => invoke('jailbreak:sideload-ipa', a),
    magiskPatch:       ()  => invoke('jailbreak:magisk-patch'),
  },
  nand: {
    android: {
      listPartitions:   a => invoke('nand:android:list-partitions', a),
      readPartition:    a => invoke('nand:android:read-partition', a),
      backupAll:        a => invoke('nand:android:backup-all', a),
      flashPartition:   a => invoke('nand:android:flash-partition', a),
      ramdiskExtract:   a => invoke('nand:android:ramdisk-extract', a),
      ramdiskRepack:    a => invoke('nand:android:ramdisk-repack', a),
      openWorkdir:      () => invoke('nand:android:open-workdir'),
      openPartitions:   () => invoke('nand:android:open-partitions'),
      ramdiskCpioExtract: () => invoke('nand:android:ramdisk-cpio-extract'),
      ramdiskCpioRepack:  () => invoke('nand:android:ramdisk-cpio-repack'),
      ramdiskTree:        () => invoke('nand:android:ramdisk-tree'),
      ramdiskReadFile:    a  => invoke('nand:android:ramdisk-read-file', a),
      ramdiskWriteFile:   a  => invoke('nand:android:ramdisk-write-file', a),
      ramdiskNewFile:     a  => invoke('nand:android:ramdisk-new-file', a),
      ramdiskDeleteFile:  a  => invoke('nand:android:ramdisk-delete-file', a),
      ramdiskOpenExtracted: () => invoke('nand:android:ramdisk-open-extracted'),
      basebandInfo:    a  => invoke('nand:android:baseband-info', a),
      basebandExtract: a  => invoke('nand:android:baseband-extract', a),
      basebandFlash:   a  => invoke('nand:android:baseband-flash', a),
      nvBackup:        a  => invoke('nand:android:nv-backup', a),
    },
    ios: {
      ramdiskInfo:   () => invoke('nand:ios:ramdisk-info'),
      enterRecovery: a  => invoke('nand:ios:enter-recovery', a),
      exitRecovery:  a  => invoke('nand:ios:exit-recovery', a),
      backupFull:    a  => invoke('nand:ios:backup-full', a),
      checkRamdiskTools:  () => invoke('nand:ios:check-ramdisk-tools'),
      toolHelp:           a  => invoke('nand:ios:tool-help', a),
      stageRamdiskBuild:  () => invoke('nand:ios:stage-ramdisk-build'),
      importRamdiskSource:() => invoke('nand:ios:import-ramdisk-source'),
      listLibimobiledeviceTools: () => invoke('nand:ios:list-libimobiledevice-tools'),
      runLibimobiledevice: a => invoke('nand:ios:run-libimobiledevice', a),
      ipswRun:          a  => invoke('nand:ios:ipsw-run', a),
      ipswPick:         () => invoke('nand:ios:ipsw-pick'),
      ipswExtractDest:  () => invoke('nand:ios:ipsw-extract-dest'),
    },
  },
  iosCustom: {
    shsh: {
      save:       a  => invoke('ios:shsh:save', a),
      list:       () => invoke('ios:shsh:list'),
      openFolder: () => invoke('ios:shsh:open-folder'),
    },
    ipsw: {
      fetchVersions:  a  => invoke('ios:ipsw:fetch-versions', a),
      download:       a  => invoke('ios:ipsw:download', a),
      extractRamdisk: a  => invoke('ios:ipsw:extract-ramdisk', a),
    },
    cydia: {
      search:     a  => invoke('ios:cydia:search', a),
      installRepo:a  => invoke('ios:cydia:install-repo', a),
    },
    bootargs:   a  => invoke('ios:bootargs:get', a),
    tweaks:     () => invoke('ios:tweaks:list'),
    themeSources: () => invoke('ios:theme:sources'),
    signedCheck: a  => invoke('ios:signed:check', a),
  },
  iosTools: {
    appstore:   { search: a => invoke('ios:appstore:search', a), appInfo: a => invoke('ios:appstore:app-info', a) },
    diag:       { fullReport: a => invoke('ios:diag:full-report', a) },
    afc:        { list: a => invoke('ios:afc:list', a) },
    contacts:   { export: a => invoke('ios:contacts:export', a) },
    network:    { wifiScan: a => invoke('ios:network:wifi-scan', a), getIp: a => invoke('ios:network:get-ip', a) },
    photos:     { count: a => invoke('ios:photos:count', a), export: a => invoke('ios:photos:export', a) },
    ssh:        { startProxy: a => invoke('ios:ssh:start-proxy', a), openTerminal: a => invoke('ios:ssh:open-terminal', a) },
    crash:      { analyze: a => invoke('ios:crash:analyze', a) },
    security:   { activationStatus: a => invoke('ios:security:activation-status', a), checkIcloudLock: a => invoke('ios:security:check-icloud-lock', a) },
    sync:       { info: a => invoke('ios:sync:info', a) },
    apps:       { listAll: a => invoke('ios:apps:list-all', a), uninstall: a => invoke('ios:apps:uninstall', a) },
    mdm:        { profilesList: a => invoke('ios:mdm:profiles-list', a) },
    restore:    { checkMode: a => invoke('ios:restore:check-mode', a) },
  },
  iosExt: {
    apps: {
      detail:     a => invoke('ios:apps:detail', a),
      backupData: a => invoke('ios:apps:backup-data', a),
      installIpa: a => invoke('ios:apps:install-ipa', a),
    },
    sysinfo:    a => invoke('ios:sysinfo:deep', a),
    syslog: {
      start:  a => invoke('ios:syslog:start', a),
      stop:   () => invoke('ios:syslog:stop'),
    },
    activation: a => invoke('ios:activation:status', a),
    afc:        a => invoke('ios:afc:list', a),
    photos:     a => invoke('ios:photos:pull', a),
    contacts:   a => invoke('ios:contacts:export', a),
    profiles: {
      list:   a => invoke('ios:profiles:list', a),
      remove: a => invoke('ios:profiles:remove', a),
    },
    certs:      a => invoke('ios:certs:list', a),
    icloud:     () => invoke('ios:icloud:bypass-info'),
    ssh: {
      connect:     a  => invoke('ios:ssh:connect', a),
      disconnect:  () => invoke('ios:ssh:disconnect'),
      openTerminal:() => invoke('ios:ssh:open-terminal'),
    },
    frida: {
      check:    a => invoke('ios:frida:server-check', a),
      listApps: a => invoke('ios:frida:list-apps', a),
      trace:    a => invoke('ios:frida:trace', a),
    },
    plist:      a => invoke('ios:plist:read-device', a),
    net:        a => invoke('ios:net:wifi-list', a),
    power: {
      sleep:    a => invoke('ios:power:sleep', a),
      restart:  a => invoke('ios:power:restart', a),
      shutdown: a => invoke('ios:power:shutdown', a),
    },
    screenshot: {
      take:       a  => invoke('ios:screenshot:take', a),
      openFolder: () => invoke('ios:screenshot:open-folder'),
    },
  },
  android: {
    bluetooth: {
      scan:   a => invoke('android:bluetooth:scan', a),
      status: a => invoke('android:bluetooth:status', a),
    },
    integrity: { check: a => invoke('android:integrity:check', a) },
    battery:   { health: a => invoke('android:battery:health', a) },
    screenrecord: {
      start: a => invoke('android:screenrecord:start', a),
      stop:  a => invoke('android:screenrecord:stop', a),
    },
    input: {
      tap:      a => invoke('android:input:tap', a),
      swipe:    a => invoke('android:input:swipe', a),
      text:     a => invoke('android:input:text', a),
      keyevent: a => invoke('android:input:keyevent', a),
    },
    notif: {
      list:  a => invoke('android:notif:list', a),
      clear: a => invoke('android:notif:clear', a),
    },
    storage:   a => invoke('android:storage:usage', a),
    apk: {
      pull:  a => invoke('android:apk:pull', a),
    },
    wireless: {
      pair: a => invoke('android:wireless:pair', a),
    },
    dumpsys: {
      battery:  a => invoke('android:dumpsys:battery', a),
      activity: a => invoke('android:dumpsys:activity', a),
      meminfo:  a => invoke('android:dumpsys:meminfo', a),
      window:   a => invoke('android:dumpsys:window', a),
    },
    info: {
      imei:    a => invoke('android:info:imei', a),
      sensors: a => invoke('android:info:sensors', a),
      cpuTemp: a => invoke('android:info:cpu-temp', a),
    },
    macro: {
      run: a => invoke('android:macro:run', a),
    },
    pm: {
      clearData: a => invoke('android:pm:clear-data', a),
      forceStop: a => invoke('android:pm:force-stop', a),
      disable:   a => invoke('android:pm:disable', a),
      enable:    a => invoke('android:pm:enable', a),
      grantAll:  a => invoke('android:pm:grant-all', a),
    },
    net: {
      ping:      a => invoke('android:net:ping', a),
      traceroute:a => invoke('android:net:traceroute', a),
      ports:     a => invoke('android:net:ports', a),
      arp:       a => invoke('android:net:arp', a),
      ipInfo:    a => invoke('android:net:ip-info', a),
    },
    files: {
      push:   a => invoke('android:files:push', a),
      delete: a => invoke('android:files:delete', a),
      mkdir:  a => invoke('android:files:mkdir', a),
      cat:    a => invoke('android:files:cat', a),
      chmod:  a => invoke('android:files:chmod', a),
    },
    settings: {
      get:  a => invoke('android:settings:get', a),
      set:  a => invoke('android:settings:set', a),
      list: a => invoke('android:settings:list', a),
    },
    dev: {
      overdraw:     a => invoke('android:dev:overdraw', a),
      layoutBounds: a => invoke('android:dev:layout-bounds', a),
      gpuRendering: a => invoke('android:dev:gpu-rendering', a),
      animScale:    a => invoke('android:dev:animator-scale', a),
      showTaps:     a => invoke('android:dev:show-taps', a),
    },
    a11y: {
      fontScale:   a => invoke('android:a11y:font-scale', a),
      displaySize: a => invoke('android:a11y:display-size', a),
      talkback:    a => invoke('android:a11y:talkback', a),
    },
  },
  iosExtra: {
    crash: {
      list:       a  => invoke('ios:crash:list', a),
      openFolder: () => invoke('ios:crash:open-folder'),
      pull:       a  => invoke('ios:crash:pull', a),
      open:       a  => invoke('ios:crash:open', a),
    },
    device: {
      getDate:  a => invoke('ios:device:get-date', a),
      setDate:  a => invoke('ios:device:set-date', a),
      getName:  a => invoke('ios:device:get-name', a),
      setName:  a => invoke('ios:device:set-name', a),
    },
    date:         { get: a => invoke('ios:date:get', a), set: a => invoke('ios:date:set', a) },
    rename:       a => invoke('ios:rename', a),
    devdisk:      { list: a => invoke('ios:devdisk:list', a), mount: a => invoke('ios:devdisk:mount', a) },
    proxy:        { start: a => invoke('ios:proxy:start', a), stop: a => invoke('ios:proxy:stop', a), list: () => invoke('ios:proxy:list') },
    notify:       a => invoke('ios:notify:send', a),
    usbmux:       a => invoke('ios:usbmux:status', a),
    mdm:          a => invoke('ios:mdm:check', a),
    respring:     a => invoke('ios:respring', a),
    battery:      a => invoke('ios:battery:detail', a),
    udidInfo:     () => invoke('ios:udid:spoofer-info'),
    ipaFind:      a => invoke('ios:ipa:find-downgrade', a),
    audit:        { generate: a => invoke('ios:audit:generate', a), open: () => invoke('ios:audit:open') },
    locationAudit:a => invoke('ios:privacy:location', a),
    screentime:   a => invoke('ios:screentime:extract', a),
    health:       a => invoke('ios:health:extract', a),
    notes:        a => invoke('ios:notes:export', a),
    appDocs:      a => invoke('ios:app:documents', a),
    notif:    a => invoke('ios:notif:list', a),
    location: a => invoke('ios:location:spoof', a),
    afc:      a => invoke('ios:afc:media-list', a),
    trollstore: {
      check:   a  => invoke('ios:trollstore:check', a),
      install: a  => invoke('ios:trollstore:install', a),
    },
    devMode:   () => invoke('ios:devmode:enable'),
    entitlements: a => invoke('ios:entitlements:get', a),
    passcode:  () => invoke('ios:passcode:bypass-methods'),
    altstore:  () => invoke('ios:altstore:check-status'),
    diag:      a  => invoke('ios:diag:mobilegestalt', a),
    backup: {
      setEncryption: a => invoke('ios:backup:set-encryption', a),
      restore:       a => invoke('ios:backup:restore', a),
    },
  },
  iosErase: {
    viaBackupTool:  a  => invoke('ios:erase:via-backup-tool', a),
    enterRecovery:  a  => invoke('ios:erase:enter-recovery-for-restore', a),
    openItunes:     () => invoke('ios:erase:open-itunes'),
    dfuGuide:       () => invoke('ios:erase:dfu-guide'),
  },
  app: {
    version:  () => invoke('app:version'),
    platform: () => invoke('app:platform'),
  },

  //    OMNI - SSH Bridge / Termux Node Manager
  ssh: {
    hostsList:    () => invoke('ssh:hosts:list'),
    hostsSave:    a  => invoke('ssh:hosts:save', a),
    hostsDelete:  a  => invoke('ssh:hosts:delete', a),
    exec:         a  => invoke('ssh:exec', a),
    shellOpen:    a  => invoke('ssh:shell:open', a),
    shellWrite:   a  => invoke('ssh:shell:write', a),
    shellResize:  a  => invoke('ssh:shell:resize', a),
    shellClose:   a  => invoke('ssh:shell:close', a),
    onShellData:  (sessionId, cb) => on('ssh:shell:data:' + sessionId, cb),
    onShellClosed:(sessionId, cb) => on('ssh:shell:closed:' + sessionId, cb),
    sftpList:     a  => invoke('ssh:sftp:list', a),
    sftpDownload: a  => invoke('ssh:sftp:download', a),
    sftpUpload:   a  => invoke('ssh:sftp:upload', a),
    sftpMkdir:    a  => invoke('ssh:sftp:mkdir', a),
    sftpDelete:   a  => invoke('ssh:sftp:delete', a),
    test:         a  => invoke('ssh:test', a),
  },

  //    OMNI - AI Assistant
  ai: {
    keyStatus:    () => invoke('ai:key:get-status'),
    keySet:       a  => invoke('ai:key:set', a),
    keyClear:     () => invoke('ai:key:clear'),
    modelsList:   () => invoke('ai:models:list'),
    convoList:    () => invoke('ai:convo:list'),
    convoLoad:    a  => invoke('ai:convo:load', a),
    convoSave:    a  => invoke('ai:convo:save', a),
    convoDelete:  a  => invoke('ai:convo:delete', a),
    chatStream:   a  => invoke('ai:chat:stream', a),
    onStream:     (streamId, cb) => on('ai:stream:' + streamId, cb),
  },

  //    OMNI - Secure Messaging + Wallet Address Book
  msg: {
    identityGet:    () => invoke('msg:identity:get'),
    contactsList:   () => invoke('msg:contacts:list'),
    contactsSave:   a  => invoke('msg:contacts:save', a),
    contactsDelete: a  => invoke('msg:contacts:delete', a),
    historyLoad:    a  => invoke('msg:history:load', a),
    historyAppend:  a  => invoke('msg:history:append', a),
    relayConnect:   a  => invoke('msg:relay:connect', a),
    relayDisconnect:() => invoke('msg:relay:disconnect'),
    relaySend:      a  => invoke('msg:relay:send', a),
    decrypt:        a  => invoke('msg:decrypt', a),
    onRelayStatus:  cb => on('msg:relay:status', cb),
    onRelayMessage: cb => on('msg:relay:message', cb),
  },
  wallet: {
    list:    () => invoke('wallet:list'),
    save:    a  => invoke('wallet:save', a),
    delete:  a  => invoke('wallet:delete', a),
    balance: a  => invoke('wallet:balance', a),
  },

  //    OMNI - Multi-chipset Bootloader Toolkit
  blt: {
    chipsetsList:    () => invoke('blt:chipsets:list'),
    detect:          () => invoke('blt:detect'),
    fastbootGetvar:  () => invoke('blt:fastboot:getvar-all'),
    fastbootUnlock:  a  => invoke('blt:fastboot:unlock', a),
    fastbootFlash:   a  => invoke('blt:fastboot:flash', a),
    heimdallDetect:  () => invoke('blt:heimdall:detect'),
    heimdallPrintPit:() => invoke('blt:heimdall:print-pit'),
    mtkRun:          a  => invoke('blt:mtk:run', a),
  },

  //    OMNI - Repo Browser / IPA Inspector (APK inspection lives in the
  //    existing Android - Dev - "APK Analyser" page instead)
  repo: {
    fetch:         a  => invoke('repo:fetch', a),
    releasesInfo:  a  => invoke('repo:releases-info', a),
    pickIpa:       () => invoke('repo:pick-ipa'),
    inspectIpa:    a  => invoke('repo:inspect-ipa', a),
  },

  openUrl: url => send('open:url', url),
  on, off: ch => ipcRenderer.removeAllListeners(ch)
})
