#!/usr/bin/env python3
"""
Write docs/PROJECT.md — everything a new session needs to know.

    python3 scripts/gen_project_doc.py            # write it
    python3 scripts/gen_project_doc.py --check    # fail if it is out of date

The prose lives in this file; the tables are DERIVED from the code — the
module map from each module's own docstring, the API surface from
core/dispatch, the tiers and policies from core/policy and core/sandbox, the
providers from core/config.

That split is the point. A hand-written architecture document is a snapshot of
what someone believed on the day they wrote it, and this project has already
shipped one lie of that shape: the manual said "six tabs" for two releases
after there were eight. Anything a machine can read, a machine reads, and the
audit gate fails if the checked-in copy has drifted from what the code says.
"""
import argparse
import ast
import io
import subprocess
import sys
from contextlib import redirect_stdout
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "PROJECT.md"
sys.path.insert(0, str(ROOT))


def _first_line(path):
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return ""
    doc = ast.get_docstring(tree) or ""
    for line in doc.splitlines():
        if line.strip():
            return line.strip()
    return ""


def module_table(folder):
    rows = []
    for p in sorted((ROOT / folder).glob("*.py")):
        if p.name == "__init__.py":
            continue
        lines = len(p.read_text(encoding="utf-8").splitlines())
        rows.append((p.name, lines, _first_line(p)))
    body = ["| Module | Lines | What it is |", "|---|---:|---|"]
    body += [f"| `{n}` | {c} | {d} |" for n, c, d in rows]
    return "\n".join(body)


def api_surface():
    from core import dispatch
    local = set(dispatch.LOCAL_ONLY)

    def mark(path):
        return " **L**" if any(path == p.rstrip("/") or path.startswith(p)
                               for p in local) else ""

    gets = sorted(dispatch._GET_PLAIN)
    posts = sorted(dispatch._POST_BODY)
    out = ["| GET | | POST | |", "|---|---|---|---|"]
    for i in range(max(len(gets), len(posts))):
        g = f"`{gets[i]}`{mark(gets[i])}" if i < len(gets) else ""
        p = f"`{posts[i]}`{mark(posts[i])}" if i < len(posts) else ""
        out.append(f"| {g} | | {p} | |")
    return "\n".join(out)


def gate_table():
    from core import policy, sandbox
    tiers = [a for a in dir(sandbox.Tier) if a.isupper()]
    ex = policy.explain()
    rows = ["| Policy | What it does |", "|---|---|"]
    for name, desc in ex["policies"].items():
        rows.append(f"| `{name}` | {desc} |")
    return "\n".join(rows), ", ".join(f"`{t}`" for t in tiers)


def providers():
    from core import config
    return (", ".join(f"`{p}`" for p in config.PROVIDERS),
            " → ".join(f"`{p}`" for p in config.ROUTING_ORDER))


def modes():
    from core import modes as m
    return ", ".join(f"`{k}`" for k in m.SPEC)


def screens():
    d = ROOT / "android-native/app/src/main/java/com/omerta/agent"
    ui = sorted(p.name for p in (d / "ui").glob("*.kt"))
    top = sorted(p.name for p in d.glob("*.java")) + \
        sorted(p.name for p in d.glob("*.kt"))
    return ", ".join(f"`{n}`" for n in ui), ", ".join(f"`{n}`" for n in top)


def version():
    import re
    m = re.search(r'^version\s*=\s*"([^"]+)"',
                  (ROOT / "pyproject.toml").read_text(encoding="utf-8"), re.M)
    return m.group(1) if m else "unknown"


def build():
    policies, tiers = gate_table()
    provs, order = providers()
    ui, top = screens()
    return f"""# OMERTA AI — the whole project

Generated by `scripts/gen_project_doc.py` at version {version()}. The tables
are read out of the code; the prose is in that script. Do not hand-edit this
file — the audit gate fails when it drifts from what the code actually says.

Read `CLAUDE.md` first: it holds the standing rules and outranks everything
here. This file is context, not instruction.

---

## What it is

An agent that runs on hardware the owner owns. It reads and writes code, drives
a real shell, inspects and builds firmware, remembers across sessions, and asks
before it acts. One tree builds three shipped things: an Android APK, a Debian
package and a Windows installer.

It does not contain a language model. It routes to one — a cloud provider with
a key, a server on the network, or a `.gguf` running on the device itself.

## The one fact that explains most of the constraints

The owner's phone is **32-bit ARM** (`armv7l`, `armeabi-v7a`, model P602).

- The APK must carry `armeabi-v7a` as well as `arm64-v8a` in one file. Shipping
  a single ABI produced eight releases that would not install on that phone.
- On-device weights do not fit, and not for want of RAM: a 32-bit process
  cannot address them. The weights screen says so per model rather than letting
  a 2 GB download fail at the end.
- Claude Code v2.x cannot run there — it ships a per-platform native binary and
  there is no 32-bit Android build. v1.0.128 is the last pure-JavaScript
  release and does run.

## Architecture

One request layer. `core/dispatch.py` routes `(method, path, query, body,
local)` and every transport goes through it:

| Transport | Used by | Notes |
|---|---|---|
| `core/httpd.py` | LAN browser, sync peers | stdlib only, token auth |
| `server.py` | desktop, richer HTTP | FastAPI; has its own route list |
| in-process (Chaquopy) | the Android app | no socket, no port, no server |
| `core/stdio_rpc.py` | desktop shell | line-delimited JSON over a pipe |

Authentication belongs to the transport; routing, the approval gate and the
wire format do not. Two copies of the routing table is how `/api/attach` once
came to be local-only on one server and open on the other.

### The approval gate

Every command is classified into a tier, and the policy decides what that tier
means. Tiers: {tiers}.

{policies}

`DENY` is unapprovable — it cannot be run by any policy, and the check is
argument-precise rather than a substring match. The editor's saves, scheduled
turns and the agent's own writes all pass through this same gate.

### What is local-only

Marked **L** in the table below. These are direct operation of the device — a
shell, the editor's writes, a sandbox that executes commands, adb to another
handset, an encrypted archive of everything, the panic wipe — and they do not
route through the approval gate, because the person is driving them. That is
precisely why they must never be drivable from another machine.

Three of them were found by exploiting them: a remote caller ran `id` as root
through the sandbox endpoint, overwrote a file through the editor endpoint, and
read `/etc/hostname` through the learning endpoint.

## The API surface

{api_surface()}

`/api/pair/claim` is deliberately absent from both columns and from the
local-only list: it is the one route that answers without a token, and only
while a pairing offer is open. Everything that keeps it narrow is in
`core/pairing.py`.

## Modules

### `core/`

{module_table("core")}

### `tools/`

{module_table("tools")}

## The Android app

Jetpack Compose. No WebView, no HTML, no JavaScript, no HTTP — the screens call
Python in the same process through `OmertaClient` → `core/dispatch`. Eight tabs:
CHAT, CHATS, CODE, GIT, LEARN, TOOLS, TERM, SETTINGS.

- UI: {ui}
- Host: {top}

`webui/` still exists, but only for reaching a backend from a LAN browser. It
is not staged into the APK, and the gate fails the build if HTML appears there.

## Models

Providers: {provs}

Routing order when set to auto: {order}

Work modes: {modes()}. `plan` and `research` genuinely withhold the tools that
change things — a mode is a statement about what the agent is allowed to do,
not a tone of voice.

Network mode `offline` removes every provider that would leave the device, and
does it by construction rather than by a later filter: the guarantee must not
depend on a second check still being right.

## Build and release

```
python3 scripts/audit.py --phase "<what you just did>"   # must pass clean
bash scripts/release.sh                                  # all three, one zip
```

`release.sh` runs the gate first, builds all three, then checks the ARTIFACTS:
that the APK carries both ABIs, that it contains no HTML, that the zip
verifies. It prints the checksums of what went into the zip, because a rebuild
is not byte-identical and quoting an earlier build's hash makes an install
block reject a download that was perfectly good.

## Decisions that look like gaps and are not

Changing any of these needs a reason, not a tidy-up.

- **`core/gitx.py` is read-only by whitelist.** The GIT tab cannot commit or
  push; those buttons hand the request to the agent so the exact command lands
  on an approval card. Two ways to move a branch, one of them ungated, is how a
  safety property stops being one.
- **A scheduled turn keeps the same approval policy as a typed one.** It stops
  at the gate and the approval waits. An agent that acts more freely when
  nobody is watching is the thing this project exists not to build.
- **The audit chain is tamper EVIDENCE, not tamper proofing**, and says so. The
  key is on the same device as the log; the value is the head digest written
  down somewhere the device cannot reach.
- **The panic wipe is not behind the gate.** A panic action that stops to ask
  does not work. It reports what it could not remove rather than claiming
  success.
- **Per-project API keys are thread-local**, not environment variables.
  Projects run concurrently, so an environment variable would be visible to all
  of them — the opposite of scoping.
- **Private chats have no recovery.** The passcode is not stored. That is the
  feature.

## What has never been verified

Stated because the project's own constitution requires it.

- **Nothing has ever run on a real handset.** Every APK has shipped on
  inspection of the built artifact alone.
- **Pairing has never been run against a second device.** The logic is tested;
  the two-device path is not.
- **The `.exe` has never been run on Windows.** It is built and inspected.

## Bugs that shaped the design

Each of these shipped, and each is why something here looks the way it does.

| What happened | What it changed |
|---|---|
| `omerta_boot.start()` took 3 args, Java passed 4; the `TypeError` was swallowed by `catch (Throwable)`. The backend was dead on every device for four releases. | The gate now checks Java↔Python call arity, and a test reintroduces the bug. |
| The web UI kept shipping inside the APK after being removed from the include list — the staging task was a `Copy`, which only adds. | Changed to `Sync`; the release script greps the built APK for HTML. |
| A `has_internet()` probe removed keyed providers, so a valid API key looked broken. | The probe now only reorders; only explicit offline mode excludes. |
| The desktop build reported itself as `channel: android` — stamped after staging. | Stamp before staging; the gate checks version integrity. |
| An install block quoted the hash of an APK built minutes before the one in the zip, so a perfectly good download was rejected. | Blocks read the `SHA256SUMS` that ships inside the zip. |
| The icon generator pushed a greyscale engraving through a saturated red ramp; at 48px the skull stopped reading as a skull. | Tints keep a desaturated midtone; contrast hardens as the target shrinks. |
| The gate's own local-only check read a fixed 400 characters and reported a disagreement between two files that agreed. | It reads to the closing parenthesis. It would equally have missed a real one. |
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the checked-in copy is stale")
    args = ap.parse_args()

    text = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("docs/PROJECT.md is out of date — run "
                  "python3 scripts/gen_project_doc.py", file=sys.stderr)
            return 1
        print("docs/PROJECT.md is current")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
